### ISSUE TITLE
Cursor can advance pass the end

### ISSUE THREAD

**Issue by Aryex** [awslabs/amazon-timestream-odbc-driver#10]
### Describe the bug

Timestream cursor can advance pass the end, causing an error. See [link](https://github.com/awslabs/amazon-timestream-odbc-driver/blob/main/src/odbc/src/timestream_cursor.cpp#L40-L48).

### Expected Behavior

When advanced pass the end, driver does not break.

### Current Behavior

It breaks.

### Reproduction Steps

Instantiate a TimestreamCursor and advance it pass the end.

### Possible Solution

Check if cursor is at the end.

### Timestream ODBC Driver version

2.0.0

### Host Operating System and version

N/A

**Comment by trevorbonas** [comment]
I have noticed this problem and I am working on a fix.

**Comment by trevorbonas** [comment]
The fix has been implemented as

```c++
bool TimestreamCursor::Increment() {
  LOG_DEBUG_MSG("Increment is called");

  if (curPos_ > 0 && iterator_ < rowVec_.end()) {
    ++iterator_;
  }
  curPos_++;
  return curPos_ <= rowVec_.size();
}
```

An integration test has also been added to confirm the fix.
