### ISSUE TITLE
SQLGetData incorrectly set strLen to SQL_NO_TOTAL 

### ISSUE THREAD

**Issue by Aryex** [awslabs/amazon-timestream-odbc-driver#19]
### Describe the bug

SQLGetData is setting strLen to SQL_NO_TOTAL when it finishes reading data or when there's no data. This causes PBI and Excel to fail to load data through the driver.

Per ODBC specs, it should not do this; SQL_NO_TOTAL is only set when the driver could not determine the data size.
- See part 7 [here](https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetdata-function?view=sql-server-ver16#retrieving-data-with-sqlgetdata).

### Expected Behavior

strLen is set to SQL_NO_TOTAL only when the data size could not be determine.

### Current Behavior

SQLGetData set strLen to SQL_NO_TOTAL when data is empty or after it finishes reading data.

### Reproduction Steps

Execute an empty query `SELECT ''` then use SQLGetData to get the column 1 data. The result should be successful and strLen = -4 (SQL_NO_TOTAL)

### Possible Solution

[This](https://github.com/awslabs/amazon-timestream-odbc-driver/blob/main/src/odbc/src/app/application_data_buffer.cpp#L286) should return 0 instead

### Timestream ODBC Driver version

2.1.1

### Host Operating System and version

Windows 11, OSX 14

**Comment by forestmvey** [comment]
Thank you for creating the issue. Closing as [PR-22](https://github.com/awslabs/amazon-timestream-odbc-driver/pull/22) has the fix for the bug.
